export default {
  SET_ORIGIN: "set-origin",
  SET_DESTINATION: "set-destination",
  SET_WEIGHT_AND_PRICE: "set-weight-and-price",
  SET_ORDERS: "set-orders",
  SET_RECEIVER: "set-receiver",
  SET_PICKUP_OPTIONS: "set-pickup-options",
  SET_PAYMENT_METHOD: "set-payment-method",
  IS_LOADING_GET_SHIPPING_COST: "is-loading-get-shipping-cost",
  SET_IS_LOADING_GET_SHIPPING_COST: "set-is-loading-get-shipping-cost",
  GET_SHIPPING_COST: "get-shipping-cost",
  GET_SHIPPING_COST_SUCCESS: "get-shipping-cost-success",
  RESET_SHIPPING: "reset-warehouses",
  REDUCE_PRODUCT_LIST: "reduce-product-list",
};
