export default {
  SET_ORIGIN: "set-origin",
  SET_SELECT_SENDER: "set-select-sender",
  SET_DESTINATION: "set-destination",
  SET_PRODUCTS: "set-prdocuts",
  SET_TOTAL_WEIGHT_ORDERS: "set-total-weight-orders",
  SET_ORDERS: "set-orders",
  SET_RECEIVER: "set-receiver",
  SET_DIMENSION: "set-dimension",
  SET_NOTES: "set-notes",
  RESET_PRODUCT_TOTAL_WEIGHT: "reset-product-total-weight",
  SET_PICKUP_OPTIONS: "set-pickup-options",
  SET_PAYMENT_METHOD: "set-payment-method",
  IS_LOADING_GET_SHIPPING_COST: "is-loading-get-shipping-cost",
  SET_IS_LOADING_GET_SHIPPING_COST: "set-is-loading-get-shipping-cost",
  GET_SHIPPING_COST: "get-shipping-cost",
  GET_SHIPPING_COST_SUCCESS: "get-shipping-cost-success",
  SET_SELECT_COURIR: "set-select-courir",
  RESET_SHIPPING: "reset-warehouses",
};
