export default {
  SET_SENDER: "set-sender-package",
  SET_RECEIVER: "set-receiver-package",
  SET_WAREHOUSE_ID: "set-warehouse-id-package",
  SET_ITEMS: "set-items-package",
  SET_ADD_ITEM: "set-add-item-package",
  SET_REMOVE_ITEM: "set-remove-item-package",
  SET_QTY_ITEM: "set-qty-item-package",
  SET_DETAIL: "set-detail-package",
  SET_SHIPPING: "set-shipping-package",
  SET_SHIPPING_INSURANCE: "set-shipping-insurance-package",
  SET_SHIPPING_COD: "set-shipping-cod-package",
  SET_ITEM_VALUE: "set-item-value-package",
  SET_ERROR: "set-error-package",

  GET_HISTORY_WAITING_PICKUP: "get-history-waiting-pickup",
  GET_HISTORY_SHIPPED: "get-history-shipped",
  GET_HISTORY_SUCCESS: "get-history-success",
  IS_LOADING_GET_HISTORY_SUCCESS: "is-loading-get-history",
  RESET_HISTORY: "reset-history",
};
